namespace ConsoleApp1;

public interface IInterface
{
    void Navegar();
};
/*
RESTRICCIONES:
NO SE PUEDEN DEFINIR CAMPOS DE CLASE
NO SE PUEDEN DEFINIR CONSTRUCTORES
NO SE PUEDEN DEFINIR DESTRUCTORES
NO SE PUEDEN  DEFINIR MODIFICADORES DE ACCESO EN LOS METODOS
NO SE PUEDEN ANIDAR CLASES NI OTRO TIPO DE ESTRUCTURAS EN LAS INTERFACES
*/